name: Build & Release IPPIS E-recruitment exam app
on:
  push:
    tags:
      - "v*" # Runs only when pushing version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build

      - name: Package App with Electron-Builder
        run: npm run dist

      - name: Upload Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
            dist/latest.yml
            dist/latest-mac.yml
            dist/latest-linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
